apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nfs-provisioner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nfs-provisioner.labels" . | nindent 4 }}
automountServiceAccountToken: true  # Explicitly required for API access
