apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "nfs-provisioner.labels" . | nindent 4 }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageClass.defaultClass | quote }}
provisioner: {{ .Values.provisionerName }}
parameters:
  archiveOnDelete: {{ .Values.storageClass.archiveOnDelete | quote }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
{{- if .Values.storageClass.mountOptions }}
mountOptions:
  {{- range .Values.storageClass.mountOptions }}
  - {{ . }}
  {{- end }}
{{- end }}
