apiVersion: v2
name: nfs-provisioner
description: A Helm chart for Kubernetes NFS provisioner compatible with UNAS Pro
type: application
version: 0.1.0
appVersion: "4.0.2"
keywords:
  - nfs
  - storage
  - provisioner
  - unas-pro
home: https://github.com/conner-s/unas-pro-kubernetes-nfs-provisioner-helm
maintainers:
  - name: conner-s
